### ISSUE TITLE
Projects using NativeWind cannot correctly process CommonJS modules after a Storybook build.

### ISSUE THREAD

**Issue by bear-ei** [storybookjs/react-native#811]
**Describe the bug**
Projects using NativeWind encounter an Uncaught ```ReferenceError: exports is not defined``` error after publishing the production web version following a Storybook build.

**To Reproduce**
Create a project that uses NativeWind, run a Storybook build, and then run the production output.

**Expected behavior**
Can correctly handle the NativeWind build.

**System:**
System:
    OS: macOS 15.6.1
    CPU: (8) x64 Intel(R) Core(TM) i5-1038NG7 CPU @ 2.00GHz
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 22.20.0 - /usr/local/opt/node@22/bin/node
    Yarn: 4.10.3 - /usr/local/opt/node@22/bin/yarn <----- active
    npm: 10.9.3 - /usr/local/opt/node@22/bin/npm
    pnpm: 9.5.0 - ~/.nvm/versions/node/v20.19.2/bin/pnpm
  Browsers:
    Chrome: 142.0.7444.135
    Safari: 18.6
  npmPackages:
    @storybook/addon-docs: ^9.1.10 => 9.1.10 
    @storybook/addon-ondevice-actions: ^9.1.4 => 9.1.4 
    @storybook/addon-ondevice-controls: ^9.1.4 => 9.1.4 
    @storybook/react-native: ^9.1.4 => 9.1.4 
    @storybook/react-native-web-vite: ^9.1.10 => 9.1.10 
    eslint-plugin-storybook: ^9.1.10 => 9.1.10 
    storybook: ^9.1.10 => 9.1.10 

**Additional context**
The issue stems from ```react-native-css-interop``` using a ```CommonJS``` module export when building the production bundle, but ```@storybook/react-native-web-vite``` appears not to correctly handle the package's export mechanism during the build process.

**Comment by dannyhw** [comment]
This seems like you might just need to update because that problem should already be resolved.

Could you update your react-native-css-interop and nativewind version to latest stable and let me know if theres any change?

**Comment by dannyhw** [comment]
You can check here for some examples on setup

https://github.com/dannyhw/react-native-web-vite-sb-examples

**Comment by bear-ei** [comment]
> You can check here for some examples on setup
> 
> https://github.com/dannyhw/react-native-web-vite-sb-examples

npmPackages:
nativewind: ^4.2.1
react-native-css-interop: "^0.2.1"
vite-plugin-rnw: "^0.0.8"


I believe the 3 relevant package versions for this issue have all been updated to the latest version. The problem still persists, and the only difference from the example you provided is that my project was created with a ```CLI```, not ```Expo```. Perhaps Expo might be smoothing over this issue somewhere in the middle. Regardless, I might still need some time to continue investigating where exactly this problem lies.


https://github.com/bear-ei/ui - This is the target library where the error is occurring.

**Comment by dannyhw** [comment]
Thing is expo doesn't enter the picture with vite since there is no vite plugin or anything from expo so it must be one of the versions or other things in the config

Could you tell me what would be the right way to reproduce the problem in that repo? I just run storybook?

**Comment by bear-ei** [comment]
> Thing is expo doesn't enter the picture with vite since there is no vite plugin or anything from expo so it must be one of the versions or other things in the config
> 
> Could you tell me what would be the right way to reproduce the problem in that repo? I just run storybook?

Running the ```yarn build-storybook``` command to build storybook-static generates a built asset, ```storybook-static/assets/iframe-xxxx.js```, which contains ```Object.defineProperty(exports, \"__esModule\", {value: !0});```. This is the culprit causing the error. However, it runs fine in the development environment when running Storybook.

**Comment by bear-ei** [comment]
After investigation, **Vite in the production environment bundles** ```doctor.js``` **from** ```react-native-css-interop``` into the build artifacts.

The code snippet in doctor.js, specifically:

`<react-native-css-interop-jsx-pragma-check /> === true`

**prevents Rollup from correctly processing the file.**

People encountering the same issue can refer to this temporary fix here:  

https://github.com/nativewind/nativewind/issues/778#issuecomment-2316112429

**Comment by dannyhw** [comment]
Thanks for the update :). I could try build in a workaround for this potentially 🤔. Will need to see how nativewind 5 will behave too.

**Comment by dannyhw** [comment]
I've pushed a workaround in vite-plugin-rnw 0.0.10 that should make it work without patching/configuration
